import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AIChat from "../components/ui/AIChat";
import BackgroundShader from "../components/canvas/BackgroundShader";
import StatusBar from "../components/ui/StatusBar";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 return (
    <html lang="en">
      <body className="bg-slate-950 antialiased">
        <BackgroundShader /> 
        {children}
        <StatusBar/>
        <AIChat />
      </body>
    </html>
  );
}
